version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: monitor-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: monitor
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitor123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/database/migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - monitor-network

  # ClickHouse数据库
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: monitor-clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: monitor
      CLICKHOUSE_USER: monitor
      CLICKHOUSE_PASSWORD: monitor123
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - monitor-network

  # Redis缓存和队列
  redis:
    image: redis:7-alpine
    container_name: monitor-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - monitor-network

  # Redis Commander (可选的Redis管理界面)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: monitor-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - monitor-network

volumes:
  mysql_data:
  clickhouse_data:
  redis_data:

networks:
  monitor-network:
    driver: bridge